### ISSUE TITLE
Not able to set Admin default password

### ISSUE THREAD

**Issue by vosuyak** [trion-development/docker-jenkins-docker-client#4]
Use case:
Looking to use this image in my Kubernetes deployment component and run via kubectl rather than the docker cmd.

The Issue:
When passing the image in my Kubernetes cluster, I'm able to land on the /login page, however, because this is running on Kubernetes and not docker, a generated password is not present on the command prompt.

Potential solution:
Is there a way to pass a temporary default password via, the -e (environment)? With this approach login proceeds to the dashboard.

![image](https://user-images.githubusercontent.com/16410052/95289815-b7846f80-0839-11eb-93b3-124612d18413.png)

**Comment by everflux** [comment]
You can get the output from the pod with the initial password using `kubectl logs <pod> -n <namespace>`
