### ISSUE TITLE
Automated plugin install no more seems to work

### ISSUE THREAD

**Issue by Riduidel** [trion-development/docker-jenkins-docker-client#7]
I'm trying your excellent distribution of Jenkins for training, and I have an issue with automated plugin install

At startup, I get

```
Configuration as Code enabled
WARN: install-plugins.sh has been removed, please switch to jenkins-plugin-cli
Configuration as Code: Installing default config
Starting /usr/local/bin/jenkins.sh as jenkins
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
```

The second line is especially interesting.

Recent versions of [Jenkins seems to provide a CLI able to install plugins](https://www.jenkins.io/doc/book/managing/plugins/#install-with-cli), provided it knows which Jenkins instance to call (I guess).

**Comment by Riduidel** [comment]
Do you want some collaboration on this subject?

**Comment by Riduidel** [comment]
Seems like it can be resolved by invoking `jenkins-plugin-cli --plugin-file /provisioning/plugins.txt` during startup.

**Comment by everflux** [comment]
If you would like to submit a pull request, I would be happy to merge it!
